language: python

python:
- 3.6
- 3.7

dist: xenial

sudo: true

services:
- mysql

branches:
  only:
  - develop

before_install:
- sudo apt-get install python3-dev

install:
- pip install --upgrade pip
- pip install -r requirements.txt
- pip install -e .
- pip install flake8
- pip install coveralls

before_script:
- flake8 django_crypto_fields
- mysql -e 'create database edc character set utf8;'

script:
- coverage run --source=django_crypto_fields manage.py test

after_success:
- coveralls
